---
apiVersion: v1
kind: ImageStream
metadata:
  name: s2i-kunkka-builder
  labels:
    app: s2i-kunkka-builder
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: blockfin/s2i-kunkka:1.0.0
